### ISSUE TITLE
Random crash out of no where on 1.12.2

### ISSUE THREAD

**Issue by BugmanBugman** [Tfarcenim/AutoAttack#1]
https://paste.dimdev.org/diwomemapi.mccrash

**Comment by Tfarcenim** [comment]
fixed

**Comment by BugmanBugman** [comment]
Still happens on ladders

https://hastebin.com/pipawukinu.rb
